fun main()
{
    println("ENter month number")
    val x= readLine()!!.toInt()
    when(x)
    {
        1->
        {
            println("January")
        }
        2->
        {
            println("Feb")
        }
        3->
        {
            println("March")
        }
        4->
        {
            println("April")
        }
        5->
        {
            println("May")
        }
        6->
        {
            println("June")
        }
        7->
        {
            println("July")
        }
        8->
        {
            println("Aug")
        }
        8->
        {
            println("Sept")
        }
        9->
        {
            println("Oct")
        }
        10->
        {
            println("Nov")
        }
        11-> {
            println("Dec")
        }
        12->
        {
            println("December")
        }
        else->
        {
            println("Invalid")
        }
    }
}